package org.eclipse.tractusx.managedidentitywallets.client.okhttp3;

import lombok.SneakyThrows;
import org.eclipse.tractusx.managedidentitywallets.client.v2.okhttp3.controllers.UserManagedIdentityWalletApiV2;
import org.eclipse.tractusx.managedidentitywallets.test.MiwTestCase;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.web.server.LocalServerPort;

/**
 * Test class for the API v2 client generated by OpenAPI Generator project 'managed-identity-wallets-client-okhttp3-v2'.
 */
public class OkHttp3ClientV2Test extends MiwTestCase {


    private UserManagedIdentityWalletApiV2 userManagedIdentityWalletApiV2 = null;

    @LocalServerPort
    private int port;

    @BeforeEach
    public void setUp() {
        userManagedIdentityWalletApiV2 = new UserManagedIdentityWalletApiV2();
        userManagedIdentityWalletApiV2.setCustomBaseUrl("http://localhost:" + port);
    }

    @Test
    @SneakyThrows
    public void getWalletTest() {
        var userWallet = userManagedIdentityWalletApiV2.userGetWallet();

        Assertions.assertNotNull(userWallet.getId());
    }
}
