package org.eclipse.tractusx.managedidentitywallets.client.resttemplate;

import org.eclipse.tractusx.managedidentitywallets.test.MiwTestCase;

/**
 * Test class for the API v2 client generated by OpenAPI Generator project 'managed-identity-wallets-client-resttemplate-v2'.
 */
public class RestTemplateClientV2Test extends MiwTestCase {

}
